import Head from "next/head";
import AddTask from "./components/AddTask";
import ToDoList from "./components/ToDoList";

export default function Home() {
  return (
    <>
      <Head>
        <title>To-do List Task</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-w-4xl mx-auto mt-2">
        {/* <div className="text-center flex flex-col gap-4 mb-10">
          <h1 className="text-2xl font-bold">To-Do List App</h1>
          <AddTask />
        </div> */}
        <ToDoList />
      </main>
    </>
  );
}
